services:
  - type: web
    name: lm-calculator
    env: static
    staticPublishPath: .
    buildCommand: ""
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
